### PR TITLE
pcache: adding prefix to bulk get with missed hits provider

### PR DESCRIPTION
**Pull request by StanimirIliev**
Adding prefix in this function is needed as when there are
missed keys, they usually are with specific prefix only for
the cache and they should be searched in origin without this
prefix

### CODE REVIEW

**Comment by mgenov** [comment]
Could you elaborate this case as it looks really strange to me. Some usage example will be helpful as I'm not find to find such in the PR.

**Comment by StanimirIliev** [comment]
In this case, first I map all locationIds with prefix to be able to search in the cache. The problem is that the returned missed keys are also with such prefix and cannot find anything from the origin
```kotlin
override fun getByIds(locationIds: List<String>): Map<String, Location> {
    return cache.getAll(
            locationIds.map { key(it) },
            CachedLocation::class.java,
            { missedKeys -> origin.getByIds(missedKeys).map { CachedLocation(it.value) } }
    ).map { it.id to adapt(it) }.toMap()
}

private fun key(locationId: String) = "aggregate_locations_$locationId"
```

**Comment by mgenov** [comment]
Doesn't look reasonable to me loading to be performed in the getAll calls. Here is an API of guava which is performing similar task:

screen shot 2018-06-27 at 16 29 25

https://github.com/google/guava/wiki/CachesExplained

e.g loading in this case is performed from an object named LoadingCache whose role is to perform and loading. 

This is how this could be executed from the client code: 

```kotlin
        val allKeys = mapOf("Name" to 5, "Age" to 3, "Country" to 2)
        val matchedKeys = mapOf("Name" to 5, "Age" to 3)
        val missedKeys = allKeys.keys - matchedKeys.keys
        //      val remaining = origin.loadAll(missedKeys) // could return empty list 
        //      return result + remaining 
        // [Country]
        println(missedKeys)
```

**Comment by StanimirIliev** [comment]
I already have a getAll function that returns results and which keys are missed. Do you mean the client code to looks like this?
```kotlin
  override fun getByIds(locationIds: List<String>): Map<String, Location> {
    val result = cache.getAll(locationIds.map { key(it) }, CachedLocation::class.java)

    return if (result.hasMissedKeys()) {
      result.hits.map { it.id to adapt(it) }.toMap().plus(origin.getByIds(result.missedKeys.map { it.removePrefix("aggregate_locations_") }))
    } else {
      result.hits.map { it.id to adapt(it) }.toMap()
    }
  }

  private fun key(locationId: String) = "aggregate_locations_$locationId"
```

**Comment by mgenov** [comment]
As I can see you are not using the same IDs for cache lookups and datastore lookups which causes and the issue. 

As it's just related to memcache it would be better getAll call to accept and prefix which to be appended to the key internally: 

```kotlin
val result = cache.getAll("aggregate_locations", locationIds, CachedLocation::class.java)
// e.g the returned Map will have locationIds as keys and not "aggregate_locations_:id". 
val missedKeys = locationIds - result.keys

val notCachedResult = origin.getByIds(missedKeys)

return result + notCachedResult
```

**Comment by StanimirIliev** [comment]
So this is fine?
```kotlin
override fun getByIds(locationIds: List<String>): Map<String, Location> {
    return cache.getAll(
            "all_locations_",// prefix
            locationIds,
            CachedLocation::class.java,
            { missedKeys -> origin.getByIds(missedKeys).map { CachedLocation(it.value) } }
    ).map { it.id to adapt(it) }.toMap()
}
```

**Comment by mgenov** [comment]
Putting: { missedKeys -> origin.getByIds(missedKeys).map { CachedLocation(it.value) } }  in the getAll calls doesn't sound right to me.

**Comment by mgenov** [comment]
If you change the name of the method to getAllOrLookup you will see that this is a method which is performing 2 things which is and the smelly part.

**Comment by StanimirIliev** [comment]
Ok, I have fixed this. Now there is only one method for getAll

**Comment by mgenov** [comment]
getAll should be available and without prefix.

**Comment by StanimirIliev** [comment]
I have added another getAll method without prefix parameter

**Review by mgenov — APPROVED** [review]
LGTM !

**Comment by mgenov** [comment]
0.0.5-SNAPSHOT is now available: https://oss.sonatype.org/content/repositories/snapshots/com/clouway/pcache/clouway-pcache-client/0.0.5-SNAPSHOT/

**Pull request merged**
