### PR TITLE
clouway-pcache-client-gae: flushCache operation implemented

### LINKED ISSUE #2: pcache-gae: allow to users to flush all cache
User should be able to flush all cache.

### PR DESCRIPTION
**Pull request by qnislavnachev**
Now user are able to flush all cache.

Fixed #2

### CODE REVIEW

**Review by mgenov — APPROVED** [review]
LGTM !

**Comment by qnislavnachev** [comment]
@mgenov Can you release a new version with these changes ?

**Comment by mgenov** [comment]
What is the case for the flush requirement ?

**Comment by qnislavnachev** [comment]
In ``` telcong.bss ``` project in ``` accounts ``` module, we are gonna separate all caches in this modules from caches which are made for the ``` modules profiles ```, ``` customer modules statuses ``` and ``` user modules statuses ```. 
These 3 ones will be cached in their own namespace, and because they are connected, when some of these are getting updated, the cache for their namespace will be cleared. That way other caches in the module will be untouched.

**Pull request merged**
